import { Router } from "express";
import authRoutes from "./authRoutes";
import userRoutes from "./userRoutes";
import orderRoutes from "./orderRoutes";
import paymentRoutes from "./paymentRoutes";
import notificationRoutes from "./notificationRoutes";
import listingRoutes from "./listingRoutes";
import categoryRoutes from "./categoryRoutes";
import serviceSellingRoutes from "./serviceSellingRoutes";
import serviceBookingRoutes from "./serviceBookingRoutes";
import otpRoutes from "./otpRoutes";
import geoRoutes from "./geoRoutes";
import adminRoutes from "./adminRoutes";
import contactRoutes from "./contactRoutes";
import reportRoutes from "./reportRoutes";
import reviewRoutes from "./reviewRoutes";
import websiteReviewRoutes from "./websiteReviewRoutes";
import bookingTestRoutes from "./bookingTestRoutes";

const router = Router();

router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/orders", orderRoutes);
router.use("/payments", paymentRoutes);
router.use("/notifications", notificationRoutes);
router.use("/listings", listingRoutes);
router.use("/categories", categoryRoutes);
router.use("/serviceselling", serviceSellingRoutes);
router.use("/servicebookings", serviceBookingRoutes);
router.use("/otp", otpRoutes);
router.use("/geo-search", geoRoutes);
router.use("/admin", adminRoutes);
router.use("/contact", contactRoutes);
router.use("/reports", reportRoutes);
router.use("/reviews", reviewRoutes);
router.use("/website-reviews", websiteReviewRoutes);
router.use("/servicebookings-test", bookingTestRoutes);

export default router;